project:
  type: book

lang: pt
book:
  title: "PG Mobilidade 360"
  subtitle: "Literacia sobre dados abertos em transportes"
  author:
   - name: "Rosa Félix"
     email: rosamfelix@tecnico.pt
     url: http://www.rosafelix.bike
     orcid: 0000-0002-5642-6006
     affiliation: "Instituto Superior Técnico - Universidade de Lisboa"
  date: today
  repo-url: https://github.com/temospena/PGmob360
  chapters:
    - index.qmd
    - summary.qmd
    - software.qmd
    - open-data.qmd
    # - data-manipulation.qmd
    - gtfs.qmd
    - slides.qmd
    - about.qmd
    - references.qmd
  page-footer:
    left: "R Félix"
    center: "PG Mobilidade 360"
    right: "Novembro 2024"
    
    
bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: show
    code-tools: true
    number-depth: 3
    toc-expand: 3
  # pdf:
  #   documentclass: scrreprt

editor: visual

google-scholar: true
